dynaconf_merge: on
default:
  bot:
    ws_port: 8443
    ws_enabled: false
  db:
    name: qgbot
    port: 5432
  logger:
    filename: qgbot.log
development:
  db:
    host: localhost
production:
  bot:
    ws_enabled: true
